### ISSUE TITLE
Teste falha em ambiente Windows

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/framework#100]
Baixei a versão 3.0.2-SNAPSHOT e ao tentar gerar um pacote o teste falha.

Segue o erro:

Tests in error:
  objectWithIncompatibleTypeShoutThrowConfigurationException(org.demoiselle.jee.configuration.ConfigurationLoaderTest): X:\xxxxxxxx\AppData\Local\Temp\demoiselle-configuration-test3478955563419289437\test2077655014794711254.properties: O arquivo já está sendo usado por outro proc(..).

Tests run: 68, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Demoiselle JEE Build ............................... SUCCESS [  6.424 s]
[INFO] Demoiselle JEE Bill of Materials ................... SUCCESS [  0.035 s]
[INFO] Demoiselle JEE Parent .............................. SUCCESS [  0.865 s]
[INFO] Demoiselle JEE Core ................................ SUCCESS [ 10.461 s]
[INFO] Demoiselle JEE Configuration ....................... FAILURE [  8.716 s]
[INFO] Demoiselle JEE Rest ................................ SKIPPED
[INFO] Demoiselle JEE Security ............................ SKIPPED
[INFO] Demoiselle JEE Security JWT ........................ SKIPPED
[INFO] Demoiselle JEE CRUD ................................ SKIPPED
[INFO] Demoiselle JEE Parent Rest ......................... SKIPPED
[INFO] Demoiselle JEE Script .............................. SKIPPED
[INFO] Demoiselle JEE Security Token ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.874 s
[INFO] Finished at: 2017-11-21T23:09:56-02:00
[INFO] Final Memory: 36M/203M
[INFO] ------------------------------------------------------------------------

**Comment by botelhojp** [comment]
Veja se você está apontando para o branch 3.0.2-SNAPSHOT, se não, baixe direto o branch
git clone -b 2.5.2-SNAPSHOT git@github.com:demoiselle/framework.git
O "master" é mais instável.

**Comment by joserenecampa** [comment]
O teste que quero fazer é justamente em uma funcionalidade que está em desenvolvimento no branch 3.0.2-SNAPSHOT.
