### ISSUE TITLE
Requisição utilizando filtros com condicional OR não funciona corretamente

### ISSUE THREAD

**Issue by clovisjunior** [demoiselle/framework#107]
Segundo a [documentação de filtros](https://demoiselle.gitbooks.io/documentacao-jee/content/crud-filtro.html) a requisição:

`$ curl -XGET http://localhost:8080/api/users?name=João 1,João 4`

Deveria tratar a consulta no banco de dados com a condicional OR

`(name = 'João 1' OU 'João 4') `

Porém no banco de dados a consulta esta sendo montada com a condicional AND.

**Comment by emobtech** [comment]
Isso já foi resolvido?

**Comment by emersonfaria** [comment]
Emobtech, conforme conversa telefônica que tivemos a pouco, e que te informei que estamos com pouco pessoal para realizar implementações, peço que se possível, você realize a implementação e faça um merge request.

**Comment by clovisjunior** [comment]
Correção aplicada na versão 3.0.4
