### ISSUE TITLE
Deadlock usando Wildfly 10.1.0.Final - Demoiselle 3.0.1

### ISSUE THREAD

**Issue by renalexster** [demoiselle/framework#118]
### Configurações do Ambiente

* Java HotSpot 64-Bit Server VM 10.0.1 (O mesmo ocorre com JVM HotSpot 1.8 e OpenJDK 1.8)
* Wildfly 10.1.0.Final (O mesmo acontece na versão 13.0.0.Final)
* Demoiselle 3.0.1

### Descrição do Problema

Meu servidor Wildfly está apresentando Threads consumindo 100% de CPU por conta de um problema que acredito **fortemente** ser de paralelismo (concorrência).

Fiz uma análise detalhada do servidor e encontrei Threads relacionadas ao demoiselle-security, especificamente CorsFilter.java e SecurityFilter.java travando o pool de Threads do parallelStream do Java (ForkJoinPool)

```
"ForkJoinPool.commonPool-worker-2" - Thread t@110
   java.lang.Thread.State: RUNNABLE
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.util.TreeMap.getEntry(TreeMap.java:343)
	at java.util.TreeMap.get(TreeMap.java:277)
	at org.jboss.resteasy.specimpl.MultivaluedTreeMap.get(MultivaluedTreeMap.java:185)
	at org.jboss.resteasy.specimpl.MultivaluedTreeMap.getOrCreate(MultivaluedTreeMap.java:71)
	at org.jboss.resteasy.specimpl.MultivaluedTreeMap.putSingle(MultivaluedTreeMap.java:64)
	at org.demoiselle.jee.security.filter.CorsFilter.lambda$filter$0(CorsFilter.java:54)
	at org.demoiselle.jee.security.filter.CorsFilter$$Lambda$320/884119018.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1751)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(ForkJoinPool.java:950)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1607)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

O que acontece é que as classes CorsFilter.java e SecurityFilter.java do demoiselle-security utilizam o **parallelStream** para realizar um put em um Map do JAX-RS javax.ws.rs.container.ContainerResponseContext (ver imagem abaixo, linha 54, **res.getHeaders().putSingle...** )

![corsfilter java](https://user-images.githubusercontent.com/12775694/41483929-4f7e8690-70b1-11e8-9d0a-1b4d5a483e72.png)

O grande problema é que a implementação do res.getHeader() do resteasy, utiliza um Map do tipo TreeMap (que não é **thread-safe**, https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html).

Portanto, o acesso concorrente no TreeMap está gerando em certo momento de saturação do sistema, um deadlock, causando _CPU load_ muito alto e consequentemente perda de performance na aplicação.

Segue abaixo o print do status da JVM no momento do Lock, e o Thread dump (Full e apenas as Threads em Lock). Além da configuração detalhada do ambiente.

![threads-jvm](https://user-images.githubusercontent.com/12775694/41484216-579d6282-70b2-11e8-8ac1-0f34463e95f6.png)

![overview-jvm](https://user-images.githubusercontent.com/12775694/41484312-bcbc6b18-70b2-11e8-9c6c-c009e085727e.png)

![monitor-jvm](https://user-images.githubusercontent.com/12775694/41484314-beb2f496-70b2-11e8-8c41-efa7f5b1b2a7.png)

[ThreadDump-FULL.txt](https://github.com/demoiselle/framework/files/2107157/ThreadDump-FULL.txt)
[ThreadsLOCK.txt](https://github.com/demoiselle/framework/files/2107158/ThreadsLOCK.txt)

**Comment by renalexster** [comment]
Complementando a informação.

Eu realizei um teste baixando o código do demoiselle e alterei a parte do parallelStream para stream(), o servidor não apresentou problemas com essa implementação.

**Comment by joaquimpedrooliveira** [comment]
@renalexster , fiz um pull request com tua sugestão: #119

**Comment by renalexster** [comment]
Olá @joaquimpedrooliveira,

Alguma previsão de quando sai o novo release do demoiselle? E se essa alteração já vai estar presente?

Obrigado.

**Comment by joaquimpedrooliveira** [comment]
@renalexster, mandei o pull request mas não faço parte do time do Demoiselle. Acredito que o @botelhojp ou o @PauloGladson possam dar essa resposta.

**Comment by botelhojp** [comment]
Como o ajuste é bem pontual, vamos aceitar o pull request e gerar snapshot hoje. Fico aguardando avaliação para geração de versão final.

**Comment by botelhojp** [comment]
Gerada versão 3.0.3-SNAPSHOT. @renalexster, você poderia fazer a mesma avaliação de desempenho para essa versão?

**Comment by renalexster** [comment]
@botelhojp,
Realizei o mesmo teste de carga de antes, usando JMeter e agora não tive problemas de _CPU load_.

![posfix](https://user-images.githubusercontent.com/12775694/41680944-7c99d0b6-74a9-11e8-906e-750de16f632c.png)

Como se pode perceber na imagem, após o encerramento do teste, o CPU volta a ficar IDLE.

Obrigado.

**Comment by renalexster** [comment]
Olá @botelhojp,

Eu realizei o teste com o stream() e o servidor se comporta sem dead lock agora. Você sabe dizer se tem previsão de quando sai um novo release nos repositórios maven?

**Comment by clovisjunior** [comment]
Olá @renalexster ,

Foi gerado a release 3.0.3, você já pode atualizar o pom.xml do projeto.

https://oss.sonatype.org/content/repositories/releases/org/demoiselle/jee/demoiselle-core/3.0.3/

Vou encerrar essa issue, qualquer coisa reabrimos.
