### ISSUE TITLE
Erro no CRUD - Filtro com atributo do tipo java.util.UUID

### ISSUE THREAD

**Issue by marcioassuncao** [demoiselle/framework#120]
Saudações.

    Estou tentando utilizar os recursos de **CRUD - Filtro** em um serviço REST implementado com Demoiselle 3.0.1.
    No meu caso, tenho uma entidade com o atributo "id" do tipo UUID. Ao tentar fazer o filtro nesse campo, utilizando "query string", dá um erro de conversão.
     Como fazer para configurar os conversores para os parâmetros na query string?

Obrigado.

**Comment by marcioassuncao** [comment]
Suspeito que o erro esteja na linha [https://github.com/demoiselle/framework/blob/4eac99c395b51e9cf8e0a57beab28e02960d6cf2/demoiselle-crud/src/main/java/org/demoiselle/jee/crud/AbstractDAO.java#L282](linha do erro)

**Comment by marcioassuncao** [comment]
Esta linha [aqui](https://github.com/demoiselle/framework/blob/4eac99c395b51e9cf8e0a57beab28e02960d6cf2/demoiselle-crud/src/main/java/org/demoiselle/jee/crud/AbstractDAO.java#L260) também apresentou um erro ao usar atributos aninhados.

**Comment by clovisjunior** [comment]
Olá @marcioassuncao ,

Apliquei a solução da versão 3.0.4 que foi publicado hoje.

A alteração do código você pode ver aqui: 
https://github.com/demoiselle/framework/commit/574be213a487375fedeb33ef5ff62327eaec14a9#diff-775cdec7a26c80d111dbd82e815266bfR311
