### ISSUE TITLE
Adicionar no Android Studio

### ISSUE THREAD

**Issue by mbslet** [demoiselle/framework#122]
Teria alguma formar de adicionar a framework no Android Studio? Andei progurando com base nas configurações porém não obtive sucesso.

**Comment by clovisjunior** [comment]
Olá @mbslet ,

O framework demoiselle é voltado para o desenvolvimento de aplicações Java EE 7 (geralmente aplicações web), eu fiquei na dúvida se você esta querendo usar o Android Studio como IDE para desenvolver aplicação Java EE (não sei se isso é possível) ou se você esta querendo usar em aplicação Android, se for o caso o Demoiselle não lhe ajudaria.
