### ISSUE TITLE
Socket Closed on call render method from FileRendererImpl

### ISSUE THREAD

**Issue by ghost** [demoiselle/framework#32]
When try to render a report with the Demoiselle Reports API, sometimes comes the error Socket Closed, this error can be resolved by changing the

@Inject
private HttpServletResponse response;

for

HttpServletResponse response = (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();

in the FileRendererImpl class

**Comment by juliancesar** [comment]
Hi, i will close this issue. If the situation mentioned above don't was resolved, please reopen.

Tks.
