### ISSUE TITLE
Infra do sourceforge instável

### ISSUE THREAD

**Issue by thiagoarrais** [demoiselle/framework#33]
Sugiro estudar a possibilidade de abandonar a infra do sourceforge para servir os componentes Maven. O sourceforge está respirando com ajuda de aparelhos e pode não ser confiável.

Meu build hoje começou a falhar com a seguinte mensagem de erro:

    Failed to transfer file: http://demoiselle.sourceforge.net/repository/release/
    br/gov/frameworkdemoiselle/component/demoiselle-validation/2.0.0/
    demoiselle-validation-2.0.0.pom.
    Return code is: 503

Se tentarmos acessar o "repositório" indicado no README, obtemos o mesmo código 503 (conforme esperado):

    $ curl -i http://demoiselle.sourceforge.net/repository/release
    HTTP/1.1 503 Service Unavailable
    Server: BigIP
    Content-Length: 5892
    Date: Tue, 21 Jul 2015 20:28:18 GMT

**Comment by esaito** [comment]
Realmente, desde a semana o ambiente está fora. Neste caso, recomendamos instalar o ambiente de desenvolvimento do Demoiselle que já fornece um repositório local com as dependências do demoiselle. 
Mas estamos trabalhando para ter outras opções de repositório. Provavelmente utilizaremos o portal do software livre.

**Comment by thiagoarrais** [comment]
Que tal o repositório central?

**Comment by esaito** [comment]
A maioria das dependências já está no central, alguns componentes como esse do validation são mais antigos e por isso não estão lá. Mas mesmo assim o nosso objetivo é ter sempre mais de um local. Atualmente seria o central e o SF. Mas houve esse "gap" para as coisas antigas. Tanto que os arquétipos e componentes mais atualizados (junit, report, mail) estão nos dois e estão bem contingenciados. 
Para resolver emergencialmente acabamos de publicar aqui:

http://demoiselle.c3sl.ufpr.br/maven/repository/release/

**Comment by thiagoarrais** [comment]
Excelente!
