### ISSUE TITLE
Discussões 3.0 - JEE

### ISSUE THREAD

**Issue by juliancesar** [demoiselle/framework#34]
Olá pessoal convido todos e participar das discussões sobre a nova versão do Framework Demoiselle.

A versão 3.0 do Demoiselle visa atender necessidades de modernização e eficiência. Assuntos como: Java 8, servidores de aplicação JEE7, uso de Microcontainers, Multitenancy entre outros, são temas presentes nas novas linhas de desenvolvimento.

Vide vídeo: https://youtu.be/bP72IQEQzhU

Deixe aqui suas expectativas e comentários sobre o assunto.

**Comment by nobredelivery** [comment]
Qual a previsão para a primeria release ?

**Comment by mfdavid** [comment]
Alguns comentários:
- Não entendi muito bem a relação entre o framework e o uso de Microcontainers e Multitenancy. Estar ou não rodando dentro de um container deveria ser transparente para o framework. Talvez um fator importante seria ser possível fazer aplicações Restfull e leves, para poder escalar com mais facilidade em um ambiente PaaS por exemplo. Não sei se é isso que vocês querem dizer.
- Se a preoupação de vocês é com as soluções do SERPRO, deveriam ter uma alta preocupação com execução de processamentos Batch, coisa que nunca vi a comunidade do Demoiselle se preocupar muito. Para aplicações web restfull as especificações do J2EE já atendem perfeitamente, não deveriam gastar muito esforço com isso. Já a parte batch, esta sim poderia ter uma dedicação mais forte. Por exemplo: o que recomandam usar para processamento batch intenso?

**Comment by botelhojp** [comment]
1. Olá @nobredelivery, lançaremos betas mensalmente. Final de setembro: beta-1, Outubro: beta-2, Novembro: rc-1. Se for bem teremos a 3.0.0 em dezembro.

2. @mfdavid, seu entendimento está correto. O tema **microcontainer** deve ser transparente ao framework. Nosso desafio é tornar o Demoiselle mais leve para rodá-lo em containers menores. Iniciamos, por exemplo, testes com o http://wildfly-swarm.io/ e estamos contentes com os resultados.

3. Estamos investigando algumas estratégias de implementação do **multitenancy**, sabemos que este assunto extrapola o desenvolvimento. A infraestrutura e as áreas de negócios tem seus próprios desafios, mas acredito que podemos contribuir com estratégias arquiteturais.

4. Sobre **processamento batch**, concordo da sua importância e podemos fomentar o assunto. O EE7 trás novidades com a JSR 352 (http://www.oracle.com/technetwork/articles/java/batch-1965499.html), além disso devemos contar com a experiência de equipes tenham vivido os desafios desse tipo de arquitetura. Espero que tenhamos mais contribuições neste assunto.

**Comment by ezequieljuliano** [comment]
Já existe algum roadmap contendo o que vai ser desenvolvido e entregue em cada versão (mensal ou final)? 

Eu lembro que haviam algumas Issues pendentes no Jira como elas ficaram?

**Comment by botelhojp** [comment]
@ezequieljuliano, publiquei o vídeo explicativo hoje: https://youtu.be/bP72IQEQzhU
Vamos direcionar a gestão do projeto no GitHub, as issues do Jira pertinentes serão também tratadas no GitHub.

**Comment by jacksonemmerich** [comment]
Usei o demoiselle por um bom tempo depois vi que faltava acompanhar as mudanças, tive que mudar para o jhipster. Que na minha opinião é o que o demoiselle quer ser. E eles acertaram ao escolher spring ao invés das especificações padrão JEE. 
https://jhipster.github.io

**Comment by jacksonemmerich** [comment]
Olha essa ferramenta de modelagem que o jhipster tem: https://jhipster.github.io/jdl-studio/ é fantastico!

**Comment by botelhojp** [comment]
Oi @jacksonemmerich, muito bacana a ferramenta de modelagem. Continuamos apostando na especificação JEE7, inclusive o Demoiselle deve abrir mão de parte dos seus códigos para delegar ao JEE7. De fato o Spring está sempre um passo na frente. Também entendo que a especificação vem evoluindo e atendendo grande parte das nossas necessidades, talvez esse seja um dos motivos para continuar apostando nela.
Fico feliz em tê-lo no grupo, esperamos contar com a sua experiência.

**Comment by lucianojs** [comment]
Uma ponta que ficou solta já no Demoiselle 2.5 foi como documentar e testar a camada REST.

O DBehave não provê suporte nativo a isto e já vi outras equipes trabalhando com SoapUI e até experimentando o Postman.
Outra coisa é como utilizar um mesmo cenário de teste projetado para ser utilizado tanto no REST quanto na Tela, sem duplicação de cenário e massa.
Com relação a documentação, atualmente nos projeto que atuo geramos no padrão Swagger automaticamente com o plugin abaixo, mas não considero a opção como ideal.
https://github.com/sdaschner/jaxrs-analyzer-maven-plugin

**Comment by mfdavid** [comment]
@lucianojs nos últimos projetos estou usando Swagger também, mas optei por deixar a documentação separada do código fonte. Estou usando o swagger editor (editor.swagger.io) e depois exporto o json para uma página estática (que deixo dentro do web-app mesmo, mas poderia estar em qualquer lugar - é só conteúdo estático mesmo).
Já participei de projetos onde deixávamos junto com código fonte (usando esse plugin), mas acho que fica meio poluido e achava ruim de fazer alterações na documentação (tinha que ficar recompilando tudo, subindo o servidor todo, etc).

**Comment by lucasa** [comment]
Obrigado @botelhojp  pela sugestão do JHipster, eu não conhecia. Passei umas boas horas estudando a solução, e para mim, é o framework mais interessante para desenvolvimento web com Java. Vou até iniciar um projeto pessoal usando ele, pela facilidade de uso.

Para colaborar com a discussão do tema Multitenancy/SaaS, gostaria de indicar o vídeo uma palestra que fiz via streaming: http://assiste.serpro.gov.br/cisl/video.php?nome=184371
A palestra aborda o tema em alto nível mas pode interessar aos recém chegados na discussão.

**Sugiro que seja aberto um tópico exclusivo para o debate das possíveis opções arquiteturais para suporte ao desenvolvimento multitanancy.**

**Comment by botelhojp** [comment]
Lançada hoje versão 3.0.0-BETA2: http://repo1.maven.org/maven2/org/demoiselle/jee/

**Comment by PamelaBeatriz** [comment]
Olá quando irão lançar a versão 3.0.0 oficial? 
Muito obrigada!

**Comment by botelhojp** [comment]
@PamelaBeatriz o milestone foi programado para 31/01/2017
https://github.com/demoiselle/framework/milestone/4

**Comment by PamelaBeatriz** [comment]
@botelhojp  Muito obrigada!!    =D

**Comment by PamelaBeatriz** [comment]
@botelhojp  Nunca utilizei o Demoiselle antes e agora estou precisando utilizar ele para um projeto no qual estou envolvida. Os líderes técnicos recomendaram utilizar a versão 3. Entretanto como ela ainda está em construção eu não sei se de fato vai ser interessante já utilizá-la ou se vai ser possível esperar sair a Release. Como estou começando do zero, posso me guiar quanto a questão de instalação e configuração do framework utilizando as informações do portal https://www.frameworkdemoiselle.gov.br/web/guest/home substituindo apenas a versão 2.5 pela versão versão 3.0.0-BETA2. O processo de configuração é similar? 

Existe algum material ou vídeo mostrando o processo de configuração para a versão 3?
Desde já muito obrigada!!!
Abraço

**Comment by botelhojp** [comment]
@PamelaBeatriz, sugiro experimentar a versão BETA2 para evitar um trabalho futuro de migração. Devemos lançar uma versão candidata nesta ou na próxima semana. Verifique se o roteiro rápido pode ajudá-la: https://demoiselle.gitbooks.io/documentacao-jee/content/roteiro_rapido.html

**Comment by PauloGladson** [comment]
@PamelaBeatriz estou fazendo um TodoList para ser usado de referência, monitora o https://github.com/PGXP/todoList

**Comment by PamelaBeatriz** [comment]
@botelhojp Obrigada. Comecei a configuração. Vou dar uma olhada nos vídeos da comunidade tbm pra poder começar a codificar alguma coisa usando a versão BETA2. 
Haverá muitas mudanças entre a versão BETA2 e a Candidata?

@PauloGladson  vou acompanhar sim. Muito obrigada!

**Comment by botelhojp** [comment]
Lançada versão experimental do Framework Demoiselle 3 (versão 3.0.0-RC1).

A partir desta versão é possível avaliar com mais estabilidade as novidades do framework que tem entrega prevista para o mês de fevereiro.

Informações adicionais com exemplos, documentação, formas de participar estão disponíveis no site http://demoiselle.io

**Comment by vbuitoni** [comment]
Na versão 2 do Demoiselle existiam filtros e uma classe Authenticator para manter a autenticação do usuário através de Token usando HEADER HTTP, para aplicações REST.

No Demoiselle 3 não encontrei implementação equivalente. Qual é a forma recomendada de se manter a autenticação do usuário em aplicações REST? Tem que implementar na mão?

Já temos uma aplicação usando Demoiselle 2 e estamos tentando migrar para o Demoiselle 3. Por enquanto estou pensando em copiar o código destas classes do Demoiselle 2 para o nosso projeto e utilizá-las. Será que é muito ruim? Existe uma forma melhor?

**Comment by botelhojp** [comment]
@vbuitoni verifique se essa documentação ajudar na dúvida https://demoiselle.gitbooks.io/documentacao-jee/content/security.html. Caso contrário ela será complementada.

**Comment by PauloGladson** [comment]
vbuitoni,

A estratégia mudou um pouco, mas sua implementação será reaproveitada. O
filtro está lá e o security context também. Vou providenciar um tutorial de
migração,  quando ficar pronto, te informo.

Em 17 de jan de 2017 12:21, "vbuitoni" <notifications@github.com> escreveu:

Na versão 2 do Demoiselle existiam filtros e uma classe Authenticator para
manter a autenticação do usuário através de Token usando HEADER HTTP, para
aplicações REST.

No Demoiselle 3 não encontrei implementação equivalente. Qual é a forma
recomendada de se manter a autenticação do usuário em aplicações REST? Tem
que implementar na mão?

Já temos uma aplicação usando Demoiselle 2 e estamos tentando migrar para o
Demoiselle 3. Por enquanto estou pensando em copiar o código destas classes
do Demoiselle 2 para o nosso projeto e utilizá-las. Será que é muito ruim?
Existe uma forma melhor?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/demoiselle/framework/issues/34#issuecomment-273177795>,
or mute the thread

**Comment by mfdavid** [comment]
Como faço para que "subir" o projeto backend do demoiselle TODO para que ele aceite requisições externas? Por padão parece aceitar apenas requisições localhost.

java -jar -Xmx128m target/todo-swarm.jar

Tem algum parâmetro que possa passar? (ao similar o -b 0.0.0.0 do jboss)

**Comment by PauloGladson** [comment]
@mfdavid 

Tenta java -jar -Xmx128m -Dswarm.bind.address=0.0.0.0 target/todo-swarm.jar

**Comment by botelhojp** [comment]
Prezados, devido a publicação da versão final, que será feita amanhã, essa issue será fechada.
Para novas discussões, favor abrir nova issues.
Agradecemos as contribuições.
