### ISSUE TITLE
Módulo de segurança para o front-end

### ISSUE THREAD

**Issue by marcelofns** [demoiselle/framework#45]
Desenvolver módulo de segurança Angular2 com as seguintes características:
- Serviços de autenticação utilizando JWT
- Diretivas de segurança que apresentam conteúdo de acordo com roles, autenticado/não autenticado
- Serviço AuthGuard que permite configuração das rotas de acordo com a autenticação

**Comment by botelhojp** [comment]
Movido para https://github.com/demoiselle/frontend/issues/3
