### ISSUE TITLE
Tratamento de Mensagens do Framework

### ISSUE THREAD

**Issue by juliancesar** [demoiselle/framework#50]

**Comment by juliancesar** [comment]
Será utilizado o Delta Spike (https://deltaspike.apache.org) para esta funcionalidade.

**Comment by juliancesar** [comment]
A documentação minima necessária para um projeto utilizar o módulo esta disponível no seguinte link da documentação:

https://demoiselle.gitbooks.io/documentacao-jee/content/core-messages.html

**Comment by juliancesar** [comment]
Rever a documentação colocando mais exemplos de uso.

**Comment by PauloGladson** [comment]
Retornar errors de banco com o sql_state, error_code
