### ISSUE TITLE
Erro a rodar qualquer projeto.

### ISSUE THREAD

**Issue by Deuzinei** [demoiselle/framework#62]
Vários desenvolvedores estão recebendo o mesmo Erro. Algém pode nos ajudar

[br.gov.frameworkdemoiselle.exception] (http-localhost/127.0.0.1:8080-2) Tratando a exceção org.jboss.weld.exceptions.WeldException

**Comment by juliancesar** [comment]
Qual o ambiente? 
* Servidor de Aplicação
* Banco de dados
* Versão do Framework
* Outras bibliotecas importadas no `pom.xml`

Aguardo.

**Comment by Deuzinei** [comment]
Qual o ambiente?

    Servidor de Aplicação e versão - jboss-eap-6.4.0
    Banco de dados e versão - Postgres 9.1
    Versão do Framework - 2.5
    Outras bibliotecas importadas no pom.xml e versões - 

Aguardo.

**Comment by botelhojp** [comment]
Passe a Stack Trace completa da exceção. Estava funcionando e parou? Em que situação acontece o erro?

**Comment by Deuzinei** [comment]
Está funcioando em outra máquina. Tentei tbm fazer uma cópia desse ambeinte que funciona e tbm não funcionou, mesmo erro.


09:35:54,690 INFO  [org.jboss.resteasy.cdi.i18n] (http-localhost/127.0.0.1:8080-2) RESTEASY006050: Found BeanManager at java:comp/BeanManager
09:35:54,802 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (http-localhost/127.0.0.1:8080-2) RESTEASY000320: Deploying javax.ws.rs.core.Application: class br.gov.serpro.srep.rest.Api$Proxy$_$$_WeldClientProxy
09:35:55,300 INFO  [org.hibernate.dialect.Dialect] (http-localhost/127.0.0.1:8080-2) HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
09:35:55,301 INFO  [org.hibernate.engine.jdbc.internal.LobCreatorBuilder] (http-localhost/127.0.0.1:8080-2) HHH000422: Disabling contextual LOB creation as connection was null
09:35:55,346 INFO  [br.gov.frameworkdemoiselle.exception] (http-localhost/127.0.0.1:8080-2) Tratando a exceção org.jboss.weld.exceptions.WeldException
09:35:55,353 INFO  [br.gov.frameworkdemoiselle.exception] (http-localhost/127.0.0.1:8080-2) Tratando a exceção org.jboss.weld.exceptions.WeldException

**Comment by botelhojp** [comment]
Pode ser um problema no ambiente de desenvolvimento.
Para verificar gere uma build (war) da aplicação via maven, não use sua IDE, publique o war direto no seu JBoss. Se funcionar, a investigação deve ser no ambiente de desenvolvimento.

**Comment by botelhojp** [comment]
Utilize um JBoss JEE7 (Wildlfy). O EAP 6.4 não é JEE 7
