### ISSUE TITLE
Desabilitar a segurança

### ISSUE THREAD

**Issue by reinaldovale** [demoiselle/framework#77]
Senhores,

O componente de segurança (autenkus) exige cookies e saml para funcionar corretamente, porém em tempo de desenvolvimento é extremamente trabalhoso.

Na versão 2.5 do demoiselle tínhamos a propriedade `demoiselle.security.enabled=false` para nos salvar.

Por favor, implementar algo semelhante na versão 3.x

Desde já agradeço.

**Comment by PauloGladson** [comment]
@reinaldovale,

Infelizmente não poderemos implementar tal alternativa, pois cria um ponto de vulnerabilidade no framework, mas nossa forma de modularizar construída na versão 3, permite que os componentes tenham suas validações específicas, então a implementação do componente autentikus, tem a possibilidade de ter esse ponto de "by pass" configurável por parâmetro algo como "authentikus.security.enabled=false", seria interessante você conversar com os mantenedores do componente sobre a inclusão dessa funcionalidade.
