### ISSUE TITLE
Implementar pesquisa do tipo "LIKE"

### ISSUE THREAD

**Issue by jefersonmiranda** [demoiselle/framework#81]
Onde algo desse tipo:

http://localhost:8080/api/users?name%fulano

deve retornar:

[
  {"id":1,"name":"Fulano da Silva", "email": "ocara@omail.com"},
  {"id":1,"name":"Ciclano Fulano", "email": "ciclano-fulano@omail.com"},
  {"id":1,"name":"Fulanous Marvelous", "email": "fulanous-marvelous@omail.com"},
]

**Comment by PauloGladson** [comment]
Segue exemplo de implementação que pode ajudar a resolver essa funcionalidade

https://github.com/demoiselle/example/blob/master/v3/cep/backend/src/main/java/app/service/LogradouroREST.java

https://github.com/demoiselle/example/blob/master/v3/cep/backend/src/main/java/app/dao/CepDAO.java

No método getListaLogradouro será feita uma consulta com like

**Comment by emobtech** [comment]
https://github.com/demoiselle/framework/pull/94

**Comment by emersonfaria** [comment]
Fechando essa issue. Problema foi tratado pela [#94](https://github.com/demoiselle/framework/pull/94)
