### ISSUE TITLE
[demoiselle-crud] NullPointerException

### ISSUE THREAD

**Issue by reinaldovale** [demoiselle/framework#93]
Na versão 3.0 do demoiselle crud está ocorrendo um NullPointerException em:

`resourceInfo.getResourceClass`

https://github.com/demoiselle/framework/blob/eec420e06e245fc406ba0ee52d369c1ccb8697f8/demoiselle-crud/src/main/java/org/demoiselle/jee/crud/pagination/PaginationHelper.java#L244

O mesmo código na versão 2.5

https://github.com/demoiselle/framework/blob/326901c4cf15938d43f341a83171a13673750c97/demoiselle-crud/src/main/java/org/demoiselle/jee/crud/pagination/PaginationHelper.java#L245

**Comment by PauloGladson** [comment]
@reinaldovale Você está usando o Wildfly10 ou o EAP 7.0.4?

**Comment by PauloGladson** [comment]
@reinaldovale Esse erro ja está corrigido na 3.0.1-SNAPSHOT, você poderia testar?

**Comment by reinaldovale** [comment]
@PauloGladson,

Estou usando o Wildfly10.
Testei com 3.0.1-SNAPSHOT e o erro não ocorre mais.
