### ISSUE TITLE
[Demoiselle-Crud] - Não retorna fields de 2º Nível via @Search

### ISSUE THREAD

**Issue by wilsonleitejr** [demoiselle/framework#96]
Olá, 

estou utilizando o Demoiselle-Crud e meu serviço está herdando de AbstractRest, fiz um override do método find e gostaria de definir quais propriedades serão retornadas, para melhor controle gostaria de deixar as propriedades definidas via anotação @Search, como descrito em https://demoiselle.gitbooks.io/documentacao-jee/content/crud-campo.html, as propriedades de 1º Nível estão retornando corretamente, porém nenhuma propriedade de 2º nível, exemplo: unidade(sigla), regional(nome), é retornada no response. Realizei um teste através do query param ?fields e desta forma os campos de 2º nível são retornados, creio que o comportamento  do @Search deve ser semelhante ao quando se utiliza ?fields.

**Comment by PauloGladson** [comment]
@wilsonleitejr Já identificamos e vamos tratar essa correção, logo te avisamos quando finalizarmos

**Comment by clovisjunior** [comment]
@wilsonleitejr foi gerado uma versão de SNAPSHOT (3.0.2-SNAPSHOT https://oss.sonatype.org/content/repositories/snapshots/org/demoiselle/jee/demoiselle-crud/3.0.2-SNAPSHOT/), aponte seu projeto para essa versão para avaliar a correção.

**Comment by wilsonleitejr** [comment]
@clovisjunior, apontei o projeto para a nova versão 3.0.2-SNAPSHOT e funcionou corretamente, retornando os campos de 2º nível. :+1:

**Comment by botelhojp** [comment]
Versão candidata gerada 3.0.2-RC1, favor testar.

**Comment by botelhojp** [comment]
Versão candidata lançada (3.0.2-RC2) favor testar
